
PSASTRO.MATCH.RADIUS 	F32 2.0    # fitting radius in pixels

PSASTRO.CHIP.NX      	S32 1      # chip-to-fpa tranformation order
PSASTRO.CHIP.NY	     	S32 1      # chip-to-fpa tranformation order

PSASTRO.CHIP.NSIGMA  	F32 3.0    # Nsigma clip for matched-fit 
PSASTRO.CHIP.NITER   	S32 3      # number of clipping interations for matched-fit 

PSASTRO.GRID.OFFSET  	F32 100.0  # maximum allowed offset for grid match
PSASTRO.GRID.SCALE   	F32  50.0  # binning scale for grid match

PSASTRO.GRID.MIN.ANGLE  F32   0.0  # starting angle
PSASTRO.GRID.MAX.ANGLE  F32   0.0  # ending angle
PSASTRO.GRID.DEL.ANGLE  F32   0.5  # steps between angle attempts

PSASTRO.STARS.MAX       S32 300    # use no more than this number of sources
