
NX            S32  2000    	 # chip dimensions
NY            S32  2000    	 # chip dimensions

NSTARS        S32  20    	 # number of fake stars to generate

# the current test output file only has the basic WCS info.  
READOUT.COL.0    F32  0		 # cell coord for readout (0,0)
READOUT.ROW.0    F32  0		 # cell coord for readout (0,0)
READOUT.COL.BIN  F32  1		 # readout col binning factor
READOUT.ROW.BIN  F32  1		 # readout row binning factor

CELL.COL.0    	 F32  0		 # chip coord for cell (0,0)
CELL.ROW.0    	 F32  0		 # chip coord for cell (0,0)

CHIP.COL.0    	 F32  0		 # FPA coord for chip (0,0)
CHIP.ROW.0    	 F32  0		 # FPA coord for chip (0,0)
CHIP.THETA    	 F32  0	         # cw rotation from chip to FPA
CHIP.PARITY.X 	 F32  1		 # x flip 
CHIP.PARITY.Y 	 F32  1		 # y flip 

FPA.THETA     	 F32  0		 # fpa row offset
FPA.COL.0  	 F32  0		 # TPA coord for FPA (0,0)
FPA.ROW.0  	 F32  0		 # TPA coord for FPA (0,0)

PLATE.SCALE	 F32  1	         # plate scale in arcsec/pixel
RA		 F32  10	 # celestial coord for TPA (0,0)
DEC     	 F32  20	 # celestial coord for TPA (0,0)
