/*
 * laptool.h
 */

#ifndef LAPTOOL_H
#define LAPTOOL_H 1

#include "pxtools.h"

typedef enum {
  LAPTOOL_MODE_NONE           = 0x0,
  LAPTOOL_MODE_DEFINESEQUENCE,
  LAPTOOL_MODE_LISTSEQUENCE,
  LAPTOOL_MODE_DEFINERUN,
  LAPTOOL_MODE_DEFINERUNBYRELEASE,
  LAPTOOL_MODE_PENDINGRUN,
  LAPTOOL_MODE_UPDATERUN,
  LAPTOOL_MODE_PENDINGEXP,
  LAPTOOL_MODE_EXPOSURES,
  LAPTOOL_MODE_STACKS,
  LAPTOOL_MODE_REVERTSASS,
  LAPTOOL_MODE_UPDATEEXP,
  LAPTOOL_MODE_DIFFCHECK,
  LAPTOOL_MODE_INACTIVEEXP,
  LAPTOOL_MODE_DEFINEGROUP,
  LAPTOOL_MODE_PENDINGGROUP,
  LAPTOOL_MODE_FILTERSFORGROUP,
  LAPTOOL_MODE_UPDATEGROUP,
  LAPTOOL_MODE_REVERTGROUP,
  LAPTOOL_MODE_LISTGROUP,
} laptoolMode;

pxConfig *laptoolConfig(pxConfig *config, int argc, char **argv);

#endif // LAPTOOL_H


