/*
 * remotetool.h
 */

#ifndef REMOTETOOL_H
#define REMOTETOOL_H 1

#include "pxtools.h"

typedef enum {
  REMOTETOOL_MODE_NONE          = 0x0,
  REMOTETOOL_MODE_DEFINEBYQUERY,
  REMOTETOOL_MODE_LISTRUN,
  REMOTETOOL_MODE_DONEPREP,
  REMOTETOOL_MODE_LISTCOMPONENT,
  REMOTETOOL_MODE_DROPCOMPONENT,
  REMOTETOOL_MODE_UPDATERUN,
  REMOTETOOL_MODE_UPDATEPOLL,
  REMOTETOOL_MODE_UPDATECOMPONENT,
  REMOTETOOL_MODE_REVERTRUN,
  REMOTETOOL_MODE_REVERTAUTH,
  REMOTETOOL_MODE_REVERTCOMPONENT,
} remotetoolMode;

pxConfig *remotetoolConfig(pxConfig *config, int argc, char **argv);

#endif // REMOTETOOL_H
