include(config.md)
dnl include(weather.md)
dnl include(skyp_transparency.md)
dnl include(skyp_absorption.md)
dnl include(skyp_emission.md)
dnl include(dimm.md)
dnl include(skyp_ir.md)
dnl include(dome.md)
dnl include(telescope.md)
dnl include(skycell.md)
include(dbversion.md)
include(summitcopy.md)
include(new.md)
include(raw.md)
include(chip.md)
include(cam.md)
include(add.md)
include(fake.md)
include(warp.md)
include(diff.md)
include(stack.md)
include(staticsky.md)
include(det.md)
include(label.md)
include(magic.md)
include(minidvodb.md)
include(mergedvodb.md)
include(calibration.md)
include(flatcorr.md)
include(dqstats.md)
include(pstamp.md)
include(dist.md)
include(rc.md)
include(receive.md)
include(publish.md)
include(background.md)
include(diffphot.md)
include(lap.md)
include(vp.md)
include(skycell.md)
include(release.md)
include(ff.md)
include(remote.md)
include(fpcam.md)
