float pseud2d (int ix, int iy, float *a, float *fa);
float pseud4d (int ix, int iy, float *a, float *fa);
float skyfun_plane (int ix, int iy, float *a, float *fa);
float chisq (float (function)(int, int, float *, float *), int *, int *, float *, float *, int, float *, float*, int, float *, float *, int);
int ConfigInit (int *argc, char **argv);
int addlims (float *star, int *jrect);
int addstar (float *instar, int iadd, int type);
char *SelectConfigFile (int *argc, char **argv, char *progname);
char *LoadConfigFile (char *filename);
char *ScanConfig (char *config, char *field, char *mode, int Nentry, ...);
char *expandline (char *line, char *config);
bool cosmic (float *star);
int dophot (void);
int ellipse (float, float, float, float *, float *, float *, float *);
int errupd (float *, int);
int fillerup (int, int, int);
float findsky (void);
bool galaxy (float *, float *, float *);
float guess1 (float *, float *, int, int);
float guess2 (float *, float *, int *, int *);
float guess3 (float *, float *, int *, int *);
int impaper2 (int);
int improve (int);
int isearch (void);
void lubksb (float **, int, int *, float *);
void ludcmp (float **, int, int *, float *);
int makemask (void);
int makenoise (void);
int mprint (int, char *, ...);
int set_verbosity (int);
int completeout (void);
int oblims (float *, int *);
bool oblit (float *);
bool oblit (float *);
int paravg (void);
float parinterp (float, float, float *);
int parupd (float *, float *, int, int);
int shape (void);
int sort (float *, int);
bool toobright (float *);
bool toofaint (float *, float *);
bool transmask (int, int, float);
float twofit (float *, float *, float *, float *);
int variparplane (void);
bool offpic (float *, int, int, float *, float *);
float newguess (float *, float *, int, int);
