#!/bin/csh -f

set disks="/data/elixir /data/elixir1 /data/elixir2 /data/elixir3 /h/skyprobe /data/ulu /data/hau /data/naupaka /data/mamane /data/naio /data/koa /data/kiawe /data/noni"

foreach f ($disks)
    set uspace = `sdf -a $f -M`
    set aspace = `sdf -c $f -M`
    echo $f $uspace $aspace | awk '{printf "%-20s %8.3f of %8.3f GB\n", $1, $2/1000, $3/1000}'
end
