#!/bin/csh -f 

# test if the vnc is alive.  if not, restart it.

if ($#argv != 0) then
 echo "USAGE: vnccheck" 
 exit 2
endif

set disp = `hostname`:1

xdpyinfo -display $disp >& /dev/null
if ($status) then
  vncstart
endif
