include ../Make.Common
CCWARN+=$(WERROR)

EXTRA_FFLAGS=-fno-automatic

include ../Make.Common
# Dependencies by Make.Common $Revision: 2.17 $

$(OBJ)/psfmargin.o: psfmargin.c psf.h
$(OBJ)/psfmoment.o: psfmoment.c psf.h
$(OBJ)/psfdonut.o: psfdonut.c psf.h
$(OBJ)/psf2dim.o: psf2dim.f psf.h
$(OBJ)/psf.o: psf.c psf.h
