/* src/nebulous.h
   Generated by wsdl2h 1.2.12 from nebulous.wsdl and typemap.dat
   2009-07-25 01:30:29 GMT
   Copyright (C) 2001-2008 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * urn:Nebulous/Server/SOAP                                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "urn:Nebulous/Server/SOAP"

*/

//gsoap ns1   schema namespace:	urn:Nebulous/Server/SOAP
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/



/// "urn:Nebulous/Server/SOAP":ArrayOfString is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct ArrayOfString
{
/// Pointer to array of char*.
    char*                               *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	SOAP 
//gsoap ns1  service type:	Nebulous_x002fServer_x002fSOAPPort 
//gsoap ns1  service port:	http://localhost:80/nebulous 
//gsoap ns1  service namespace:	urn:Nebulous/Server/SOAP 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage NebulousServer Definitions

@section NebulousServer_bindings Bindings
  - @ref SOAP

*/

/**

@page SOAP Binding "SOAP"

@section SOAP_operations Operations of Binding  "SOAP"
  - @ref ns1__create_USCOREobject
  - @ref ns1__rename_USCOREobject
  - @ref ns1__swap_USCOREobjects
  - @ref ns1__replicate_USCOREobject
  - @ref ns1__lock_USCOREobject
  - @ref ns1__unlock_USCOREobject
  - @ref ns1__setxattr_USCOREobject
  - @ref ns1__getxattr_USCOREobject
  - @ref ns1__listxattr_USCOREobject
  - @ref ns1__removexattr_USCOREobject
  - @ref ns1__find_USCOREobjects
  - @ref ns1__find_USCOREinstances
  - @ref ns1__delete_USCOREinstance
  - @ref ns1__stat_USCOREobject
  - @ref ns1__chmod_USCOREobject
  - @ref ns1__prune_USCOREobject

@section SOAP_ports Endpoints of Binding  "SOAP"
  - http://localhost:80/nebulous

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * SOAP                                                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * ns1__create_USCOREobject                                                   *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__create_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#create_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__create_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               volume,
    // response parameters:
    char*                              *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__create_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               volume,
    // response parameters:
    char*                              *result
  );
@endcode

*/

//gsoap ns1  service method-style:	create_USCOREobject rpc
//gsoap ns1  service method-encoding:	create_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	create_USCOREobject urn:Nebulous/Server/SOAP#create_object
int ns1__create_USCOREobject(
    char*                               key,	///< Request parameter
    char*                               volume,	///< Request parameter
    char*                              *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__rename_USCOREobject                                                   *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__rename_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#rename_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__rename_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key1,
    char*                               key2,
    // response parameters:
    int                                *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__rename_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key1,
    char*                               key2,
    // response parameters:
    int                                *result
  );
@endcode

*/

//gsoap ns1  service method-style:	rename_USCOREobject rpc
//gsoap ns1  service method-encoding:	rename_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	rename_USCOREobject urn:Nebulous/Server/SOAP#rename_object
int ns1__rename_USCOREobject(
    char*                               key1,	///< Request parameter
    char*                               key2,	///< Request parameter
    int                                *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__swap_USCOREobjects                                                    *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__swap_USCOREobjects" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#swap_objects"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__swap_USCOREobjects(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key1,
    char*                               key2,
    // response parameters:
    char*                              *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__swap_USCOREobjects(
    struct soap *soap,
    // request parameters:
    char*                               key1,
    char*                               key2,
    // response parameters:
    char*                              *result
  );
@endcode

*/

//gsoap ns1  service method-style:	swap_USCOREobjects rpc
//gsoap ns1  service method-encoding:	swap_USCOREobjects http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	swap_USCOREobjects urn:Nebulous/Server/SOAP#swap_objects
int ns1__swap_USCOREobjects(
    char*                               key1,	///< Request parameter
    char*                               key2,	///< Request parameter
    char*                              *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__replicate_USCOREobject                                                *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__replicate_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#replicate_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__replicate_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               volume,
    // response parameters:
    char*                              *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__replicate_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               volume,
    // response parameters:
    char*                              *result
  );
@endcode

*/

//gsoap ns1  service method-style:	replicate_USCOREobject rpc
//gsoap ns1  service method-encoding:	replicate_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	replicate_USCOREobject urn:Nebulous/Server/SOAP#replicate_object
int ns1__replicate_USCOREobject(
    char*                               key,	///< Request parameter
    char*                               volume,	///< Request parameter
    char*                              *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__lock_USCOREobject                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__lock_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#lock_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__lock_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               type,
    // response parameters:
    int                                *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__lock_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               type,
    // response parameters:
    int                                *result
  );
@endcode

*/

//gsoap ns1  service method-style:	lock_USCOREobject rpc
//gsoap ns1  service method-encoding:	lock_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	lock_USCOREobject urn:Nebulous/Server/SOAP#lock_object
int ns1__lock_USCOREobject(
    char*                               key,	///< Request parameter
    char*                               type,	///< Request parameter
    int                                *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__unlock_USCOREobject                                                   *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__unlock_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#unlock_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__unlock_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               type,
    // response parameters:
    int                                *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__unlock_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               type,
    // response parameters:
    int                                *result
  );
@endcode

*/

//gsoap ns1  service method-style:	unlock_USCOREobject rpc
//gsoap ns1  service method-encoding:	unlock_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	unlock_USCOREobject urn:Nebulous/Server/SOAP#unlock_object
int ns1__unlock_USCOREobject(
    char*                               key,	///< Request parameter
    char*                               type,	///< Request parameter
    int                                *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__setxattr_USCOREobject                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__setxattr_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#setxattr_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__setxattr_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               name,
    char*                               value,
    char*                               flags,
    // response parameters:
    int                                *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__setxattr_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               name,
    char*                               value,
    char*                               flags,
    // response parameters:
    int                                *result
  );
@endcode

*/

//gsoap ns1  service method-style:	setxattr_USCOREobject rpc
//gsoap ns1  service method-encoding:	setxattr_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	setxattr_USCOREobject urn:Nebulous/Server/SOAP#setxattr_object
int ns1__setxattr_USCOREobject(
    char*                               key,	///< Request parameter
    char*                               name,	///< Request parameter
    char*                               value,	///< Request parameter
    char*                               flags,	///< Request parameter
    int                                *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__getxattr_USCOREobject                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__getxattr_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#getxattr_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__getxattr_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               name,
    // response parameters:
    char*                              *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__getxattr_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               name,
    // response parameters:
    char*                              *result
  );
@endcode

*/

//gsoap ns1  service method-style:	getxattr_USCOREobject rpc
//gsoap ns1  service method-encoding:	getxattr_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	getxattr_USCOREobject urn:Nebulous/Server/SOAP#getxattr_object
int ns1__getxattr_USCOREobject(
    char*                               key,	///< Request parameter
    char*                               name,	///< Request parameter
    char*                              *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__listxattr_USCOREobject                                                *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns1__listxattr_USCOREobjectResponse" of service binding "SOAP" operation "ns1__listxattr_USCOREobject"
struct ns1__listxattr_USCOREobjectResponse
{
    struct ArrayOfString*               result;
};

/// Operation "ns1__listxattr_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#listxattr_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__listxattr_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    // response parameters:
    struct ns1__listxattr_USCOREobjectResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__listxattr_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    // response parameters:
    struct ns1__listxattr_USCOREobjectResponse*
  );
@endcode

*/

//gsoap ns1  service method-style:	listxattr_USCOREobject rpc
//gsoap ns1  service method-encoding:	listxattr_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	listxattr_USCOREobject urn:Nebulous/Server/SOAP#listxattr_object
int ns1__listxattr_USCOREobject(
    char*                               key,	///< Request parameter
    struct ns1__listxattr_USCOREobjectResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__removexattr_USCOREobject                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__removexattr_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#removexattr_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__removexattr_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               name,
    // response parameters:
    int                                *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__removexattr_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               name,
    // response parameters:
    int                                *result
  );
@endcode

*/

//gsoap ns1  service method-style:	removexattr_USCOREobject rpc
//gsoap ns1  service method-encoding:	removexattr_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	removexattr_USCOREobject urn:Nebulous/Server/SOAP#removexattr_object
int ns1__removexattr_USCOREobject(
    char*                               key,	///< Request parameter
    char*                               name,	///< Request parameter
    int                                *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__find_USCOREobjects                                                    *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns1__find_USCOREobjectsResponse" of service binding "SOAP" operation "ns1__find_USCOREobjects"
struct ns1__find_USCOREobjectsResponse
{
    struct ArrayOfString*               result;
};

/// Operation "ns1__find_USCOREobjects" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#find_objects"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__find_USCOREobjects(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               pattern,
    // response parameters:
    struct ns1__find_USCOREobjectsResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__find_USCOREobjects(
    struct soap *soap,
    // request parameters:
    char*                               pattern,
    // response parameters:
    struct ns1__find_USCOREobjectsResponse*
  );
@endcode

*/

//gsoap ns1  service method-style:	find_USCOREobjects rpc
//gsoap ns1  service method-encoding:	find_USCOREobjects http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	find_USCOREobjects urn:Nebulous/Server/SOAP#find_objects
int ns1__find_USCOREobjects(
    char*                               pattern,	///< Request parameter
    struct ns1__find_USCOREobjectsResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__find_USCOREinstances                                                  *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns1__find_USCOREinstancesResponse" of service binding "SOAP" operation "ns1__find_USCOREinstances"
struct ns1__find_USCOREinstancesResponse
{
    struct ArrayOfString*               result;
};

/// Operation "ns1__find_USCOREinstances" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#find_instances"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__find_USCOREinstances(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               volume,
    // response parameters:
    struct ns1__find_USCOREinstancesResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__find_USCOREinstances(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               volume,
    // response parameters:
    struct ns1__find_USCOREinstancesResponse*
  );
@endcode

*/

//gsoap ns1  service method-style:	find_USCOREinstances rpc
//gsoap ns1  service method-encoding:	find_USCOREinstances http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	find_USCOREinstances urn:Nebulous/Server/SOAP#find_instances
int ns1__find_USCOREinstances(
    char*                               key,	///< Request parameter
    char*                               volume,	///< Request parameter
    struct ns1__find_USCOREinstancesResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__delete_USCOREinstance                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__delete_USCOREinstance" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#delete_instance"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__delete_USCOREinstance(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    char*                               uri,
    // response parameters:
    int                                *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__delete_USCOREinstance(
    struct soap *soap,
    // request parameters:
    char*                               key,
    char*                               uri,
    // response parameters:
    int                                *result
  );
@endcode

*/

//gsoap ns1  service method-style:	delete_USCOREinstance rpc
//gsoap ns1  service method-encoding:	delete_USCOREinstance http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	delete_USCOREinstance urn:Nebulous/Server/SOAP#delete_instance
int ns1__delete_USCOREinstance(
    char*                               key,	///< Request parameter
    char*                               uri,	///< Request parameter
    int                                *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__stat_USCOREobject                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns1__stat_USCOREobjectResponse" of service binding "SOAP" operation "ns1__stat_USCOREobject"
struct ns1__stat_USCOREobjectResponse
{
    struct ArrayOfString*               result;
};

/// Operation "ns1__stat_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#stat_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__stat_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    // response parameters:
    struct ns1__stat_USCOREobjectResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__stat_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    // response parameters:
    struct ns1__stat_USCOREobjectResponse*
  );
@endcode

*/

//gsoap ns1  service method-style:	stat_USCOREobject rpc
//gsoap ns1  service method-encoding:	stat_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	stat_USCOREobject urn:Nebulous/Server/SOAP#stat_object
int ns1__stat_USCOREobject(
    char*                               key,	///< Request parameter
    struct ns1__stat_USCOREobjectResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__chmod_USCOREobject                                                    *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__chmod_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#chmod_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__chmod_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    int                                 mode,
    // response parameters:
    int                                *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__chmod_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    int                                 mode,
    // response parameters:
    int                                *result
  );
@endcode

*/

//gsoap ns1  service method-style:	chmod_USCOREobject rpc
//gsoap ns1  service method-encoding:	chmod_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	chmod_USCOREobject urn:Nebulous/Server/SOAP#chmod_object
int ns1__chmod_USCOREobject(
    char*                               key,	///< Request parameter
    int                                 mode,	///< Request parameter
    int                                *result	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * ns1__prune_USCOREobject                                                    *
 *                                                                            *
\******************************************************************************/


/// Operation "ns1__prune_USCOREobject" of service binding "SOAP"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="urn:Nebulous/Server/SOAP#prune_object"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__prune_USCOREobject(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               key,
    // response parameters:
    int                                *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__prune_USCOREobject(
    struct soap *soap,
    // request parameters:
    char*                               key,
    // response parameters:
    int                                *result
  );
@endcode

*/

//gsoap ns1  service method-style:	prune_USCOREobject rpc
//gsoap ns1  service method-encoding:	prune_USCOREobject http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	prune_USCOREobject urn:Nebulous/Server/SOAP#prune_object
int ns1__prune_USCOREobject(
    char*                               key,	///< Request parameter
    int                                *result	///< Response parameter
);

/* End of src/nebulous.h */
