/* soapStub.h
   Generated by gSOAP 2.7.12 from src/nebulous.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_ArrayOfString
#define SOAP_TYPE_ArrayOfString (7)
/* SOAP encoded array of xsd:string schema type: */
struct ArrayOfString
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREobjectResponse
#define SOAP_TYPE_ns1__create_USCOREobjectResponse (10)
/* ns1:create_objectResponse */
struct ns1__create_USCOREobjectResponse
{
	char **result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__create_USCOREobject
#define SOAP_TYPE_ns1__create_USCOREobject (11)
/* ns1:create_object */
struct ns1__create_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
	char *volume;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__rename_USCOREobjectResponse
#define SOAP_TYPE_ns1__rename_USCOREobjectResponse (14)
/* ns1:rename_objectResponse */
struct ns1__rename_USCOREobjectResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__rename_USCOREobject
#define SOAP_TYPE_ns1__rename_USCOREobject (15)
/* ns1:rename_object */
struct ns1__rename_USCOREobject
{
	char *key1;	/* optional element of type xsd:string */
	char *key2;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__swap_USCOREobjectsResponse
#define SOAP_TYPE_ns1__swap_USCOREobjectsResponse (17)
/* ns1:swap_objectsResponse */
struct ns1__swap_USCOREobjectsResponse
{
	char **result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__swap_USCOREobjects
#define SOAP_TYPE_ns1__swap_USCOREobjects (18)
/* ns1:swap_objects */
struct ns1__swap_USCOREobjects
{
	char *key1;	/* optional element of type xsd:string */
	char *key2;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__replicate_USCOREobjectResponse
#define SOAP_TYPE_ns1__replicate_USCOREobjectResponse (20)
/* ns1:replicate_objectResponse */
struct ns1__replicate_USCOREobjectResponse
{
	char **result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__replicate_USCOREobject
#define SOAP_TYPE_ns1__replicate_USCOREobject (21)
/* ns1:replicate_object */
struct ns1__replicate_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
	char *volume;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__lock_USCOREobjectResponse
#define SOAP_TYPE_ns1__lock_USCOREobjectResponse (23)
/* ns1:lock_objectResponse */
struct ns1__lock_USCOREobjectResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__lock_USCOREobject
#define SOAP_TYPE_ns1__lock_USCOREobject (24)
/* ns1:lock_object */
struct ns1__lock_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__unlock_USCOREobjectResponse
#define SOAP_TYPE_ns1__unlock_USCOREobjectResponse (26)
/* ns1:unlock_objectResponse */
struct ns1__unlock_USCOREobjectResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__unlock_USCOREobject
#define SOAP_TYPE_ns1__unlock_USCOREobject (27)
/* ns1:unlock_object */
struct ns1__unlock_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__setxattr_USCOREobjectResponse
#define SOAP_TYPE_ns1__setxattr_USCOREobjectResponse (29)
/* ns1:setxattr_objectResponse */
struct ns1__setxattr_USCOREobjectResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__setxattr_USCOREobject
#define SOAP_TYPE_ns1__setxattr_USCOREobject (30)
/* ns1:setxattr_object */
struct ns1__setxattr_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
	char *name;	/* optional element of type xsd:string */
	char *value;	/* optional element of type xsd:string */
	char *flags;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getxattr_USCOREobjectResponse
#define SOAP_TYPE_ns1__getxattr_USCOREobjectResponse (32)
/* ns1:getxattr_objectResponse */
struct ns1__getxattr_USCOREobjectResponse
{
	char **result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getxattr_USCOREobject
#define SOAP_TYPE_ns1__getxattr_USCOREobject (33)
/* ns1:getxattr_object */
struct ns1__getxattr_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__listxattr_USCOREobjectResponse
#define SOAP_TYPE_ns1__listxattr_USCOREobjectResponse (34)
/* ns1:listxattr_objectResponse */
struct ns1__listxattr_USCOREobjectResponse
{
	struct ArrayOfString *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__listxattr_USCOREobject
#define SOAP_TYPE_ns1__listxattr_USCOREobject (38)
/* ns1:listxattr_object */
struct ns1__listxattr_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__removexattr_USCOREobjectResponse
#define SOAP_TYPE_ns1__removexattr_USCOREobjectResponse (40)
/* ns1:removexattr_objectResponse */
struct ns1__removexattr_USCOREobjectResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__removexattr_USCOREobject
#define SOAP_TYPE_ns1__removexattr_USCOREobject (41)
/* ns1:removexattr_object */
struct ns1__removexattr_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
	char *name;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__find_USCOREobjectsResponse
#define SOAP_TYPE_ns1__find_USCOREobjectsResponse (42)
/* ns1:find_objectsResponse */
struct ns1__find_USCOREobjectsResponse
{
	struct ArrayOfString *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__find_USCOREobjects
#define SOAP_TYPE_ns1__find_USCOREobjects (45)
/* ns1:find_objects */
struct ns1__find_USCOREobjects
{
	char *pattern;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__find_USCOREinstancesResponse
#define SOAP_TYPE_ns1__find_USCOREinstancesResponse (46)
/* ns1:find_instancesResponse */
struct ns1__find_USCOREinstancesResponse
{
	struct ArrayOfString *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__find_USCOREinstances
#define SOAP_TYPE_ns1__find_USCOREinstances (49)
/* ns1:find_instances */
struct ns1__find_USCOREinstances
{
	char *key;	/* optional element of type xsd:string */
	char *volume;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__delete_USCOREinstanceResponse
#define SOAP_TYPE_ns1__delete_USCOREinstanceResponse (51)
/* ns1:delete_instanceResponse */
struct ns1__delete_USCOREinstanceResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__delete_USCOREinstance
#define SOAP_TYPE_ns1__delete_USCOREinstance (52)
/* ns1:delete_instance */
struct ns1__delete_USCOREinstance
{
	char *key;	/* optional element of type xsd:string */
	char *uri;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__stat_USCOREobjectResponse
#define SOAP_TYPE_ns1__stat_USCOREobjectResponse (53)
/* ns1:stat_objectResponse */
struct ns1__stat_USCOREobjectResponse
{
	struct ArrayOfString *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__stat_USCOREobject
#define SOAP_TYPE_ns1__stat_USCOREobject (56)
/* ns1:stat_object */
struct ns1__stat_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__chmod_USCOREobjectResponse
#define SOAP_TYPE_ns1__chmod_USCOREobjectResponse (58)
/* ns1:chmod_objectResponse */
struct ns1__chmod_USCOREobjectResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__chmod_USCOREobject
#define SOAP_TYPE_ns1__chmod_USCOREobject (59)
/* ns1:chmod_object */
struct ns1__chmod_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
	int mode;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__prune_USCOREobjectResponse
#define SOAP_TYPE_ns1__prune_USCOREobjectResponse (61)
/* ns1:prune_objectResponse */
struct ns1__prune_USCOREobjectResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__prune_USCOREobject
#define SOAP_TYPE_ns1__prune_USCOREobject (62)
/* ns1:prune_object */
struct ns1__prune_USCOREobject
{
	char *key;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (63)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (64)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (66)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (69)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (70)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns1__create_USCOREobject(struct soap*, char *key, char *volume, char **result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__rename_USCOREobject(struct soap*, char *key1, char *key2, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__swap_USCOREobjects(struct soap*, char *key1, char *key2, char **result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__replicate_USCOREobject(struct soap*, char *key, char *volume, char **result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__lock_USCOREobject(struct soap*, char *key, char *type, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__unlock_USCOREobject(struct soap*, char *key, char *type, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__setxattr_USCOREobject(struct soap*, char *key, char *name, char *value, char *flags, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__getxattr_USCOREobject(struct soap*, char *key, char *name, char **result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__listxattr_USCOREobject(struct soap*, char *key, struct ns1__listxattr_USCOREobjectResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 ns1__removexattr_USCOREobject(struct soap*, char *key, char *name, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__find_USCOREobjects(struct soap*, char *pattern, struct ns1__find_USCOREobjectsResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 ns1__find_USCOREinstances(struct soap*, char *key, char *volume, struct ns1__find_USCOREinstancesResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 ns1__delete_USCOREinstance(struct soap*, char *key, char *uri, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__stat_USCOREobject(struct soap*, char *key, struct ns1__stat_USCOREobjectResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 ns1__chmod_USCOREobject(struct soap*, char *key, int mode, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ns1__prune_USCOREobject(struct soap*, char *key, int *result);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__create_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *volume, char **result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__rename_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key1, char *key2, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__swap_USCOREobjects(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key1, char *key2, char **result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__replicate_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *volume, char **result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__lock_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *type, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__unlock_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *type, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__setxattr_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *name, char *value, char *flags, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getxattr_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *name, char **result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__listxattr_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, struct ns1__listxattr_USCOREobjectResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__removexattr_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *name, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__find_USCOREobjects(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *pattern, struct ns1__find_USCOREobjectsResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__find_USCOREinstances(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *volume, struct ns1__find_USCOREinstancesResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__delete_USCOREinstance(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, char *uri, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__stat_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, struct ns1__stat_USCOREobjectResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__chmod_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, int mode, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__prune_USCOREobject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *key, int *result);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__create_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__rename_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__swap_USCOREobjects(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__replicate_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__lock_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__unlock_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__setxattr_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__getxattr_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__listxattr_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__removexattr_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__find_USCOREobjects(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__find_USCOREinstances(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__delete_USCOREinstance(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__stat_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__chmod_USCOREobject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__prune_USCOREobject(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
