/* soapServer.c
   Generated by gSOAP 2.7.12 from src/nebulous.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.7.12 2009-07-25 01:30:29 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:create_object"))
		return soap_serve_ns1__create_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:rename_object"))
		return soap_serve_ns1__rename_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:swap_objects"))
		return soap_serve_ns1__swap_USCOREobjects(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:replicate_object"))
		return soap_serve_ns1__replicate_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:lock_object"))
		return soap_serve_ns1__lock_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:unlock_object"))
		return soap_serve_ns1__unlock_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:setxattr_object"))
		return soap_serve_ns1__setxattr_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getxattr_object"))
		return soap_serve_ns1__getxattr_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:listxattr_object"))
		return soap_serve_ns1__listxattr_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:removexattr_object"))
		return soap_serve_ns1__removexattr_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:find_objects"))
		return soap_serve_ns1__find_USCOREobjects(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:find_instances"))
		return soap_serve_ns1__find_USCOREinstances(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:delete_instance"))
		return soap_serve_ns1__delete_USCOREinstance(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:stat_object"))
		return soap_serve_ns1__stat_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:chmod_object"))
		return soap_serve_ns1__chmod_USCOREobject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:prune_object"))
		return soap_serve_ns1__prune_USCOREobject(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__create_USCOREobject(struct soap *soap)
{	struct ns1__create_USCOREobject soap_tmp_ns1__create_USCOREobject;
	struct ns1__create_USCOREobjectResponse soap_tmp_ns1__create_USCOREobjectResponse;
	char * soap_tmp_string;
	soap_default_ns1__create_USCOREobjectResponse(soap, &soap_tmp_ns1__create_USCOREobjectResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__create_USCOREobjectResponse.result = &soap_tmp_string;
	soap_default_ns1__create_USCOREobject(soap, &soap_tmp_ns1__create_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__create_USCOREobject(soap, &soap_tmp_ns1__create_USCOREobject, "ns1:create_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__create_USCOREobject(soap, soap_tmp_ns1__create_USCOREobject.key, soap_tmp_ns1__create_USCOREobject.volume, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__create_USCOREobjectResponse(soap, &soap_tmp_ns1__create_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__create_USCOREobjectResponse(soap, &soap_tmp_ns1__create_USCOREobjectResponse, "ns1:create_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__create_USCOREobjectResponse(soap, &soap_tmp_ns1__create_USCOREobjectResponse, "ns1:create_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__rename_USCOREobject(struct soap *soap)
{	struct ns1__rename_USCOREobject soap_tmp_ns1__rename_USCOREobject;
	struct ns1__rename_USCOREobjectResponse soap_tmp_ns1__rename_USCOREobjectResponse;
	int soap_tmp_int;
	soap_default_ns1__rename_USCOREobjectResponse(soap, &soap_tmp_ns1__rename_USCOREobjectResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__rename_USCOREobjectResponse.result = &soap_tmp_int;
	soap_default_ns1__rename_USCOREobject(soap, &soap_tmp_ns1__rename_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__rename_USCOREobject(soap, &soap_tmp_ns1__rename_USCOREobject, "ns1:rename_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__rename_USCOREobject(soap, soap_tmp_ns1__rename_USCOREobject.key1, soap_tmp_ns1__rename_USCOREobject.key2, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__rename_USCOREobjectResponse(soap, &soap_tmp_ns1__rename_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__rename_USCOREobjectResponse(soap, &soap_tmp_ns1__rename_USCOREobjectResponse, "ns1:rename_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__rename_USCOREobjectResponse(soap, &soap_tmp_ns1__rename_USCOREobjectResponse, "ns1:rename_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__swap_USCOREobjects(struct soap *soap)
{	struct ns1__swap_USCOREobjects soap_tmp_ns1__swap_USCOREobjects;
	struct ns1__swap_USCOREobjectsResponse soap_tmp_ns1__swap_USCOREobjectsResponse;
	char * soap_tmp_string;
	soap_default_ns1__swap_USCOREobjectsResponse(soap, &soap_tmp_ns1__swap_USCOREobjectsResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__swap_USCOREobjectsResponse.result = &soap_tmp_string;
	soap_default_ns1__swap_USCOREobjects(soap, &soap_tmp_ns1__swap_USCOREobjects);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__swap_USCOREobjects(soap, &soap_tmp_ns1__swap_USCOREobjects, "ns1:swap_objects", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__swap_USCOREobjects(soap, soap_tmp_ns1__swap_USCOREobjects.key1, soap_tmp_ns1__swap_USCOREobjects.key2, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__swap_USCOREobjectsResponse(soap, &soap_tmp_ns1__swap_USCOREobjectsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__swap_USCOREobjectsResponse(soap, &soap_tmp_ns1__swap_USCOREobjectsResponse, "ns1:swap_objectsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__swap_USCOREobjectsResponse(soap, &soap_tmp_ns1__swap_USCOREobjectsResponse, "ns1:swap_objectsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__replicate_USCOREobject(struct soap *soap)
{	struct ns1__replicate_USCOREobject soap_tmp_ns1__replicate_USCOREobject;
	struct ns1__replicate_USCOREobjectResponse soap_tmp_ns1__replicate_USCOREobjectResponse;
	char * soap_tmp_string;
	soap_default_ns1__replicate_USCOREobjectResponse(soap, &soap_tmp_ns1__replicate_USCOREobjectResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__replicate_USCOREobjectResponse.result = &soap_tmp_string;
	soap_default_ns1__replicate_USCOREobject(soap, &soap_tmp_ns1__replicate_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__replicate_USCOREobject(soap, &soap_tmp_ns1__replicate_USCOREobject, "ns1:replicate_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__replicate_USCOREobject(soap, soap_tmp_ns1__replicate_USCOREobject.key, soap_tmp_ns1__replicate_USCOREobject.volume, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__replicate_USCOREobjectResponse(soap, &soap_tmp_ns1__replicate_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__replicate_USCOREobjectResponse(soap, &soap_tmp_ns1__replicate_USCOREobjectResponse, "ns1:replicate_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__replicate_USCOREobjectResponse(soap, &soap_tmp_ns1__replicate_USCOREobjectResponse, "ns1:replicate_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__lock_USCOREobject(struct soap *soap)
{	struct ns1__lock_USCOREobject soap_tmp_ns1__lock_USCOREobject;
	struct ns1__lock_USCOREobjectResponse soap_tmp_ns1__lock_USCOREobjectResponse;
	int soap_tmp_int;
	soap_default_ns1__lock_USCOREobjectResponse(soap, &soap_tmp_ns1__lock_USCOREobjectResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__lock_USCOREobjectResponse.result = &soap_tmp_int;
	soap_default_ns1__lock_USCOREobject(soap, &soap_tmp_ns1__lock_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__lock_USCOREobject(soap, &soap_tmp_ns1__lock_USCOREobject, "ns1:lock_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__lock_USCOREobject(soap, soap_tmp_ns1__lock_USCOREobject.key, soap_tmp_ns1__lock_USCOREobject.type, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__lock_USCOREobjectResponse(soap, &soap_tmp_ns1__lock_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__lock_USCOREobjectResponse(soap, &soap_tmp_ns1__lock_USCOREobjectResponse, "ns1:lock_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__lock_USCOREobjectResponse(soap, &soap_tmp_ns1__lock_USCOREobjectResponse, "ns1:lock_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__unlock_USCOREobject(struct soap *soap)
{	struct ns1__unlock_USCOREobject soap_tmp_ns1__unlock_USCOREobject;
	struct ns1__unlock_USCOREobjectResponse soap_tmp_ns1__unlock_USCOREobjectResponse;
	int soap_tmp_int;
	soap_default_ns1__unlock_USCOREobjectResponse(soap, &soap_tmp_ns1__unlock_USCOREobjectResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__unlock_USCOREobjectResponse.result = &soap_tmp_int;
	soap_default_ns1__unlock_USCOREobject(soap, &soap_tmp_ns1__unlock_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__unlock_USCOREobject(soap, &soap_tmp_ns1__unlock_USCOREobject, "ns1:unlock_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__unlock_USCOREobject(soap, soap_tmp_ns1__unlock_USCOREobject.key, soap_tmp_ns1__unlock_USCOREobject.type, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__unlock_USCOREobjectResponse(soap, &soap_tmp_ns1__unlock_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__unlock_USCOREobjectResponse(soap, &soap_tmp_ns1__unlock_USCOREobjectResponse, "ns1:unlock_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__unlock_USCOREobjectResponse(soap, &soap_tmp_ns1__unlock_USCOREobjectResponse, "ns1:unlock_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__setxattr_USCOREobject(struct soap *soap)
{	struct ns1__setxattr_USCOREobject soap_tmp_ns1__setxattr_USCOREobject;
	struct ns1__setxattr_USCOREobjectResponse soap_tmp_ns1__setxattr_USCOREobjectResponse;
	int soap_tmp_int;
	soap_default_ns1__setxattr_USCOREobjectResponse(soap, &soap_tmp_ns1__setxattr_USCOREobjectResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__setxattr_USCOREobjectResponse.result = &soap_tmp_int;
	soap_default_ns1__setxattr_USCOREobject(soap, &soap_tmp_ns1__setxattr_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__setxattr_USCOREobject(soap, &soap_tmp_ns1__setxattr_USCOREobject, "ns1:setxattr_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__setxattr_USCOREobject(soap, soap_tmp_ns1__setxattr_USCOREobject.key, soap_tmp_ns1__setxattr_USCOREobject.name, soap_tmp_ns1__setxattr_USCOREobject.value, soap_tmp_ns1__setxattr_USCOREobject.flags, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__setxattr_USCOREobjectResponse(soap, &soap_tmp_ns1__setxattr_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__setxattr_USCOREobjectResponse(soap, &soap_tmp_ns1__setxattr_USCOREobjectResponse, "ns1:setxattr_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__setxattr_USCOREobjectResponse(soap, &soap_tmp_ns1__setxattr_USCOREobjectResponse, "ns1:setxattr_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__getxattr_USCOREobject(struct soap *soap)
{	struct ns1__getxattr_USCOREobject soap_tmp_ns1__getxattr_USCOREobject;
	struct ns1__getxattr_USCOREobjectResponse soap_tmp_ns1__getxattr_USCOREobjectResponse;
	char * soap_tmp_string;
	soap_default_ns1__getxattr_USCOREobjectResponse(soap, &soap_tmp_ns1__getxattr_USCOREobjectResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__getxattr_USCOREobjectResponse.result = &soap_tmp_string;
	soap_default_ns1__getxattr_USCOREobject(soap, &soap_tmp_ns1__getxattr_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__getxattr_USCOREobject(soap, &soap_tmp_ns1__getxattr_USCOREobject, "ns1:getxattr_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__getxattr_USCOREobject(soap, soap_tmp_ns1__getxattr_USCOREobject.key, soap_tmp_ns1__getxattr_USCOREobject.name, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__getxattr_USCOREobjectResponse(soap, &soap_tmp_ns1__getxattr_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getxattr_USCOREobjectResponse(soap, &soap_tmp_ns1__getxattr_USCOREobjectResponse, "ns1:getxattr_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getxattr_USCOREobjectResponse(soap, &soap_tmp_ns1__getxattr_USCOREobjectResponse, "ns1:getxattr_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__listxattr_USCOREobject(struct soap *soap)
{	struct ns1__listxattr_USCOREobject soap_tmp_ns1__listxattr_USCOREobject;
	struct ns1__listxattr_USCOREobjectResponse _param_1;
	soap_default_ns1__listxattr_USCOREobjectResponse(soap, &_param_1);
	soap_default_ns1__listxattr_USCOREobject(soap, &soap_tmp_ns1__listxattr_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__listxattr_USCOREobject(soap, &soap_tmp_ns1__listxattr_USCOREobject, "ns1:listxattr_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__listxattr_USCOREobject(soap, soap_tmp_ns1__listxattr_USCOREobject.key, &_param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__listxattr_USCOREobjectResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__listxattr_USCOREobjectResponse(soap, &_param_1, "ns1:listxattr_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__listxattr_USCOREobjectResponse(soap, &_param_1, "ns1:listxattr_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__removexattr_USCOREobject(struct soap *soap)
{	struct ns1__removexattr_USCOREobject soap_tmp_ns1__removexattr_USCOREobject;
	struct ns1__removexattr_USCOREobjectResponse soap_tmp_ns1__removexattr_USCOREobjectResponse;
	int soap_tmp_int;
	soap_default_ns1__removexattr_USCOREobjectResponse(soap, &soap_tmp_ns1__removexattr_USCOREobjectResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__removexattr_USCOREobjectResponse.result = &soap_tmp_int;
	soap_default_ns1__removexattr_USCOREobject(soap, &soap_tmp_ns1__removexattr_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__removexattr_USCOREobject(soap, &soap_tmp_ns1__removexattr_USCOREobject, "ns1:removexattr_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__removexattr_USCOREobject(soap, soap_tmp_ns1__removexattr_USCOREobject.key, soap_tmp_ns1__removexattr_USCOREobject.name, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__removexattr_USCOREobjectResponse(soap, &soap_tmp_ns1__removexattr_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__removexattr_USCOREobjectResponse(soap, &soap_tmp_ns1__removexattr_USCOREobjectResponse, "ns1:removexattr_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__removexattr_USCOREobjectResponse(soap, &soap_tmp_ns1__removexattr_USCOREobjectResponse, "ns1:removexattr_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__find_USCOREobjects(struct soap *soap)
{	struct ns1__find_USCOREobjects soap_tmp_ns1__find_USCOREobjects;
	struct ns1__find_USCOREobjectsResponse _param_2;
	soap_default_ns1__find_USCOREobjectsResponse(soap, &_param_2);
	soap_default_ns1__find_USCOREobjects(soap, &soap_tmp_ns1__find_USCOREobjects);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__find_USCOREobjects(soap, &soap_tmp_ns1__find_USCOREobjects, "ns1:find_objects", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__find_USCOREobjects(soap, soap_tmp_ns1__find_USCOREobjects.pattern, &_param_2);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__find_USCOREobjectsResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__find_USCOREobjectsResponse(soap, &_param_2, "ns1:find_objectsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__find_USCOREobjectsResponse(soap, &_param_2, "ns1:find_objectsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__find_USCOREinstances(struct soap *soap)
{	struct ns1__find_USCOREinstances soap_tmp_ns1__find_USCOREinstances;
	struct ns1__find_USCOREinstancesResponse _param_3;
	soap_default_ns1__find_USCOREinstancesResponse(soap, &_param_3);
	soap_default_ns1__find_USCOREinstances(soap, &soap_tmp_ns1__find_USCOREinstances);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__find_USCOREinstances(soap, &soap_tmp_ns1__find_USCOREinstances, "ns1:find_instances", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__find_USCOREinstances(soap, soap_tmp_ns1__find_USCOREinstances.key, soap_tmp_ns1__find_USCOREinstances.volume, &_param_3);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__find_USCOREinstancesResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__find_USCOREinstancesResponse(soap, &_param_3, "ns1:find_instancesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__find_USCOREinstancesResponse(soap, &_param_3, "ns1:find_instancesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__delete_USCOREinstance(struct soap *soap)
{	struct ns1__delete_USCOREinstance soap_tmp_ns1__delete_USCOREinstance;
	struct ns1__delete_USCOREinstanceResponse soap_tmp_ns1__delete_USCOREinstanceResponse;
	int soap_tmp_int;
	soap_default_ns1__delete_USCOREinstanceResponse(soap, &soap_tmp_ns1__delete_USCOREinstanceResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__delete_USCOREinstanceResponse.result = &soap_tmp_int;
	soap_default_ns1__delete_USCOREinstance(soap, &soap_tmp_ns1__delete_USCOREinstance);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__delete_USCOREinstance(soap, &soap_tmp_ns1__delete_USCOREinstance, "ns1:delete_instance", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__delete_USCOREinstance(soap, soap_tmp_ns1__delete_USCOREinstance.key, soap_tmp_ns1__delete_USCOREinstance.uri, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__delete_USCOREinstanceResponse(soap, &soap_tmp_ns1__delete_USCOREinstanceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__delete_USCOREinstanceResponse(soap, &soap_tmp_ns1__delete_USCOREinstanceResponse, "ns1:delete_instanceResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__delete_USCOREinstanceResponse(soap, &soap_tmp_ns1__delete_USCOREinstanceResponse, "ns1:delete_instanceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__stat_USCOREobject(struct soap *soap)
{	struct ns1__stat_USCOREobject soap_tmp_ns1__stat_USCOREobject;
	struct ns1__stat_USCOREobjectResponse _param_4;
	soap_default_ns1__stat_USCOREobjectResponse(soap, &_param_4);
	soap_default_ns1__stat_USCOREobject(soap, &soap_tmp_ns1__stat_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__stat_USCOREobject(soap, &soap_tmp_ns1__stat_USCOREobject, "ns1:stat_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__stat_USCOREobject(soap, soap_tmp_ns1__stat_USCOREobject.key, &_param_4);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__stat_USCOREobjectResponse(soap, &_param_4);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__stat_USCOREobjectResponse(soap, &_param_4, "ns1:stat_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__stat_USCOREobjectResponse(soap, &_param_4, "ns1:stat_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__chmod_USCOREobject(struct soap *soap)
{	struct ns1__chmod_USCOREobject soap_tmp_ns1__chmod_USCOREobject;
	struct ns1__chmod_USCOREobjectResponse soap_tmp_ns1__chmod_USCOREobjectResponse;
	int soap_tmp_int;
	soap_default_ns1__chmod_USCOREobjectResponse(soap, &soap_tmp_ns1__chmod_USCOREobjectResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__chmod_USCOREobjectResponse.result = &soap_tmp_int;
	soap_default_ns1__chmod_USCOREobject(soap, &soap_tmp_ns1__chmod_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__chmod_USCOREobject(soap, &soap_tmp_ns1__chmod_USCOREobject, "ns1:chmod_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__chmod_USCOREobject(soap, soap_tmp_ns1__chmod_USCOREobject.key, soap_tmp_ns1__chmod_USCOREobject.mode, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__chmod_USCOREobjectResponse(soap, &soap_tmp_ns1__chmod_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__chmod_USCOREobjectResponse(soap, &soap_tmp_ns1__chmod_USCOREobjectResponse, "ns1:chmod_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__chmod_USCOREobjectResponse(soap, &soap_tmp_ns1__chmod_USCOREobjectResponse, "ns1:chmod_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__prune_USCOREobject(struct soap *soap)
{	struct ns1__prune_USCOREobject soap_tmp_ns1__prune_USCOREobject;
	struct ns1__prune_USCOREobjectResponse soap_tmp_ns1__prune_USCOREobjectResponse;
	int soap_tmp_int;
	soap_default_ns1__prune_USCOREobjectResponse(soap, &soap_tmp_ns1__prune_USCOREobjectResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns1__prune_USCOREobjectResponse.result = &soap_tmp_int;
	soap_default_ns1__prune_USCOREobject(soap, &soap_tmp_ns1__prune_USCOREobject);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns1__prune_USCOREobject(soap, &soap_tmp_ns1__prune_USCOREobject, "ns1:prune_object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__prune_USCOREobject(soap, soap_tmp_ns1__prune_USCOREobject.key, &soap_tmp_int);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__prune_USCOREobjectResponse(soap, &soap_tmp_ns1__prune_USCOREobjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__prune_USCOREobjectResponse(soap, &soap_tmp_ns1__prune_USCOREobjectResponse, "ns1:prune_objectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__prune_USCOREobjectResponse(soap, &soap_tmp_ns1__prune_USCOREobjectResponse, "ns1:prune_objectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapServer.c */
