/* soapH.h
   Generated by gSOAP 2.7.12 from src/nebulous.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_ns1__prune_USCOREobject
#define SOAP_TYPE_ns1__prune_USCOREobject (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__prune_USCOREobject(struct soap*, struct ns1__prune_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__prune_USCOREobject(struct soap*, const struct ns1__prune_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__prune_USCOREobject(struct soap*, const struct ns1__prune_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__prune_USCOREobject(struct soap*, const char*, int, const struct ns1__prune_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__prune_USCOREobject * SOAP_FMAC4 soap_get_ns1__prune_USCOREobject(struct soap*, struct ns1__prune_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__prune_USCOREobject * SOAP_FMAC4 soap_in_ns1__prune_USCOREobject(struct soap*, const char*, struct ns1__prune_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__prune_USCOREobjectResponse
#define SOAP_TYPE_ns1__prune_USCOREobjectResponse (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__prune_USCOREobjectResponse(struct soap*, struct ns1__prune_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__prune_USCOREobjectResponse(struct soap*, const struct ns1__prune_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__prune_USCOREobjectResponse(struct soap*, const struct ns1__prune_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__prune_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__prune_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__prune_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__prune_USCOREobjectResponse(struct soap*, struct ns1__prune_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__prune_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__prune_USCOREobjectResponse(struct soap*, const char*, struct ns1__prune_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__chmod_USCOREobject
#define SOAP_TYPE_ns1__chmod_USCOREobject (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__chmod_USCOREobject(struct soap*, struct ns1__chmod_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__chmod_USCOREobject(struct soap*, const struct ns1__chmod_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__chmod_USCOREobject(struct soap*, const struct ns1__chmod_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__chmod_USCOREobject(struct soap*, const char*, int, const struct ns1__chmod_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__chmod_USCOREobject * SOAP_FMAC4 soap_get_ns1__chmod_USCOREobject(struct soap*, struct ns1__chmod_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__chmod_USCOREobject * SOAP_FMAC4 soap_in_ns1__chmod_USCOREobject(struct soap*, const char*, struct ns1__chmod_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__chmod_USCOREobjectResponse
#define SOAP_TYPE_ns1__chmod_USCOREobjectResponse (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__chmod_USCOREobjectResponse(struct soap*, struct ns1__chmod_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__chmod_USCOREobjectResponse(struct soap*, const struct ns1__chmod_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__chmod_USCOREobjectResponse(struct soap*, const struct ns1__chmod_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__chmod_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__chmod_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__chmod_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__chmod_USCOREobjectResponse(struct soap*, struct ns1__chmod_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__chmod_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__chmod_USCOREobjectResponse(struct soap*, const char*, struct ns1__chmod_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__stat_USCOREobject
#define SOAP_TYPE_ns1__stat_USCOREobject (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__stat_USCOREobject(struct soap*, struct ns1__stat_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__stat_USCOREobject(struct soap*, const struct ns1__stat_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__stat_USCOREobject(struct soap*, const struct ns1__stat_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__stat_USCOREobject(struct soap*, const char*, int, const struct ns1__stat_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__stat_USCOREobject * SOAP_FMAC4 soap_get_ns1__stat_USCOREobject(struct soap*, struct ns1__stat_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__stat_USCOREobject * SOAP_FMAC4 soap_in_ns1__stat_USCOREobject(struct soap*, const char*, struct ns1__stat_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__stat_USCOREobjectResponse
#define SOAP_TYPE_ns1__stat_USCOREobjectResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__stat_USCOREobjectResponse(struct soap*, struct ns1__stat_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__stat_USCOREobjectResponse(struct soap*, const struct ns1__stat_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__stat_USCOREobjectResponse(struct soap*, const struct ns1__stat_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__stat_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__stat_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__stat_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__stat_USCOREobjectResponse(struct soap*, struct ns1__stat_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__stat_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__stat_USCOREobjectResponse(struct soap*, const char*, struct ns1__stat_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__delete_USCOREinstance
#define SOAP_TYPE_ns1__delete_USCOREinstance (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__delete_USCOREinstance(struct soap*, struct ns1__delete_USCOREinstance *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__delete_USCOREinstance(struct soap*, const struct ns1__delete_USCOREinstance *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__delete_USCOREinstance(struct soap*, const struct ns1__delete_USCOREinstance *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__delete_USCOREinstance(struct soap*, const char*, int, const struct ns1__delete_USCOREinstance *, const char*);
SOAP_FMAC3 struct ns1__delete_USCOREinstance * SOAP_FMAC4 soap_get_ns1__delete_USCOREinstance(struct soap*, struct ns1__delete_USCOREinstance *, const char*, const char*);
SOAP_FMAC3 struct ns1__delete_USCOREinstance * SOAP_FMAC4 soap_in_ns1__delete_USCOREinstance(struct soap*, const char*, struct ns1__delete_USCOREinstance *, const char*);

#ifndef SOAP_TYPE_ns1__delete_USCOREinstanceResponse
#define SOAP_TYPE_ns1__delete_USCOREinstanceResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__delete_USCOREinstanceResponse(struct soap*, struct ns1__delete_USCOREinstanceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__delete_USCOREinstanceResponse(struct soap*, const struct ns1__delete_USCOREinstanceResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__delete_USCOREinstanceResponse(struct soap*, const struct ns1__delete_USCOREinstanceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__delete_USCOREinstanceResponse(struct soap*, const char*, int, const struct ns1__delete_USCOREinstanceResponse *, const char*);
SOAP_FMAC3 struct ns1__delete_USCOREinstanceResponse * SOAP_FMAC4 soap_get_ns1__delete_USCOREinstanceResponse(struct soap*, struct ns1__delete_USCOREinstanceResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__delete_USCOREinstanceResponse * SOAP_FMAC4 soap_in_ns1__delete_USCOREinstanceResponse(struct soap*, const char*, struct ns1__delete_USCOREinstanceResponse *, const char*);

#ifndef SOAP_TYPE_ns1__find_USCOREinstances
#define SOAP_TYPE_ns1__find_USCOREinstances (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__find_USCOREinstances(struct soap*, struct ns1__find_USCOREinstances *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__find_USCOREinstances(struct soap*, const struct ns1__find_USCOREinstances *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__find_USCOREinstances(struct soap*, const struct ns1__find_USCOREinstances *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__find_USCOREinstances(struct soap*, const char*, int, const struct ns1__find_USCOREinstances *, const char*);
SOAP_FMAC3 struct ns1__find_USCOREinstances * SOAP_FMAC4 soap_get_ns1__find_USCOREinstances(struct soap*, struct ns1__find_USCOREinstances *, const char*, const char*);
SOAP_FMAC3 struct ns1__find_USCOREinstances * SOAP_FMAC4 soap_in_ns1__find_USCOREinstances(struct soap*, const char*, struct ns1__find_USCOREinstances *, const char*);

#ifndef SOAP_TYPE_ns1__find_USCOREinstancesResponse
#define SOAP_TYPE_ns1__find_USCOREinstancesResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__find_USCOREinstancesResponse(struct soap*, struct ns1__find_USCOREinstancesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__find_USCOREinstancesResponse(struct soap*, const struct ns1__find_USCOREinstancesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__find_USCOREinstancesResponse(struct soap*, const struct ns1__find_USCOREinstancesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__find_USCOREinstancesResponse(struct soap*, const char*, int, const struct ns1__find_USCOREinstancesResponse *, const char*);
SOAP_FMAC3 struct ns1__find_USCOREinstancesResponse * SOAP_FMAC4 soap_get_ns1__find_USCOREinstancesResponse(struct soap*, struct ns1__find_USCOREinstancesResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__find_USCOREinstancesResponse * SOAP_FMAC4 soap_in_ns1__find_USCOREinstancesResponse(struct soap*, const char*, struct ns1__find_USCOREinstancesResponse *, const char*);

#ifndef SOAP_TYPE_ns1__find_USCOREobjects
#define SOAP_TYPE_ns1__find_USCOREobjects (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__find_USCOREobjects(struct soap*, struct ns1__find_USCOREobjects *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__find_USCOREobjects(struct soap*, const struct ns1__find_USCOREobjects *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__find_USCOREobjects(struct soap*, const struct ns1__find_USCOREobjects *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__find_USCOREobjects(struct soap*, const char*, int, const struct ns1__find_USCOREobjects *, const char*);
SOAP_FMAC3 struct ns1__find_USCOREobjects * SOAP_FMAC4 soap_get_ns1__find_USCOREobjects(struct soap*, struct ns1__find_USCOREobjects *, const char*, const char*);
SOAP_FMAC3 struct ns1__find_USCOREobjects * SOAP_FMAC4 soap_in_ns1__find_USCOREobjects(struct soap*, const char*, struct ns1__find_USCOREobjects *, const char*);

#ifndef SOAP_TYPE_ns1__find_USCOREobjectsResponse
#define SOAP_TYPE_ns1__find_USCOREobjectsResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__find_USCOREobjectsResponse(struct soap*, struct ns1__find_USCOREobjectsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__find_USCOREobjectsResponse(struct soap*, const struct ns1__find_USCOREobjectsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__find_USCOREobjectsResponse(struct soap*, const struct ns1__find_USCOREobjectsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__find_USCOREobjectsResponse(struct soap*, const char*, int, const struct ns1__find_USCOREobjectsResponse *, const char*);
SOAP_FMAC3 struct ns1__find_USCOREobjectsResponse * SOAP_FMAC4 soap_get_ns1__find_USCOREobjectsResponse(struct soap*, struct ns1__find_USCOREobjectsResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__find_USCOREobjectsResponse * SOAP_FMAC4 soap_in_ns1__find_USCOREobjectsResponse(struct soap*, const char*, struct ns1__find_USCOREobjectsResponse *, const char*);

#ifndef SOAP_TYPE_ns1__removexattr_USCOREobject
#define SOAP_TYPE_ns1__removexattr_USCOREobject (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__removexattr_USCOREobject(struct soap*, struct ns1__removexattr_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__removexattr_USCOREobject(struct soap*, const struct ns1__removexattr_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__removexattr_USCOREobject(struct soap*, const struct ns1__removexattr_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__removexattr_USCOREobject(struct soap*, const char*, int, const struct ns1__removexattr_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__removexattr_USCOREobject * SOAP_FMAC4 soap_get_ns1__removexattr_USCOREobject(struct soap*, struct ns1__removexattr_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__removexattr_USCOREobject * SOAP_FMAC4 soap_in_ns1__removexattr_USCOREobject(struct soap*, const char*, struct ns1__removexattr_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__removexattr_USCOREobjectResponse
#define SOAP_TYPE_ns1__removexattr_USCOREobjectResponse (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__removexattr_USCOREobjectResponse(struct soap*, struct ns1__removexattr_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__removexattr_USCOREobjectResponse(struct soap*, const struct ns1__removexattr_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__removexattr_USCOREobjectResponse(struct soap*, const struct ns1__removexattr_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__removexattr_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__removexattr_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__removexattr_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__removexattr_USCOREobjectResponse(struct soap*, struct ns1__removexattr_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__removexattr_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__removexattr_USCOREobjectResponse(struct soap*, const char*, struct ns1__removexattr_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__listxattr_USCOREobject
#define SOAP_TYPE_ns1__listxattr_USCOREobject (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__listxattr_USCOREobject(struct soap*, struct ns1__listxattr_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__listxattr_USCOREobject(struct soap*, const struct ns1__listxattr_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__listxattr_USCOREobject(struct soap*, const struct ns1__listxattr_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__listxattr_USCOREobject(struct soap*, const char*, int, const struct ns1__listxattr_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__listxattr_USCOREobject * SOAP_FMAC4 soap_get_ns1__listxattr_USCOREobject(struct soap*, struct ns1__listxattr_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__listxattr_USCOREobject * SOAP_FMAC4 soap_in_ns1__listxattr_USCOREobject(struct soap*, const char*, struct ns1__listxattr_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__listxattr_USCOREobjectResponse
#define SOAP_TYPE_ns1__listxattr_USCOREobjectResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__listxattr_USCOREobjectResponse(struct soap*, struct ns1__listxattr_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__listxattr_USCOREobjectResponse(struct soap*, const struct ns1__listxattr_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__listxattr_USCOREobjectResponse(struct soap*, const struct ns1__listxattr_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__listxattr_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__listxattr_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__listxattr_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__listxattr_USCOREobjectResponse(struct soap*, struct ns1__listxattr_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__listxattr_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__listxattr_USCOREobjectResponse(struct soap*, const char*, struct ns1__listxattr_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__getxattr_USCOREobject
#define SOAP_TYPE_ns1__getxattr_USCOREobject (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getxattr_USCOREobject(struct soap*, struct ns1__getxattr_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getxattr_USCOREobject(struct soap*, const struct ns1__getxattr_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getxattr_USCOREobject(struct soap*, const struct ns1__getxattr_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getxattr_USCOREobject(struct soap*, const char*, int, const struct ns1__getxattr_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__getxattr_USCOREobject * SOAP_FMAC4 soap_get_ns1__getxattr_USCOREobject(struct soap*, struct ns1__getxattr_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__getxattr_USCOREobject * SOAP_FMAC4 soap_in_ns1__getxattr_USCOREobject(struct soap*, const char*, struct ns1__getxattr_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__getxattr_USCOREobjectResponse
#define SOAP_TYPE_ns1__getxattr_USCOREobjectResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__getxattr_USCOREobjectResponse(struct soap*, struct ns1__getxattr_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__getxattr_USCOREobjectResponse(struct soap*, const struct ns1__getxattr_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__getxattr_USCOREobjectResponse(struct soap*, const struct ns1__getxattr_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getxattr_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__getxattr_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__getxattr_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__getxattr_USCOREobjectResponse(struct soap*, struct ns1__getxattr_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__getxattr_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__getxattr_USCOREobjectResponse(struct soap*, const char*, struct ns1__getxattr_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__setxattr_USCOREobject
#define SOAP_TYPE_ns1__setxattr_USCOREobject (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__setxattr_USCOREobject(struct soap*, struct ns1__setxattr_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__setxattr_USCOREobject(struct soap*, const struct ns1__setxattr_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__setxattr_USCOREobject(struct soap*, const struct ns1__setxattr_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__setxattr_USCOREobject(struct soap*, const char*, int, const struct ns1__setxattr_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__setxattr_USCOREobject * SOAP_FMAC4 soap_get_ns1__setxattr_USCOREobject(struct soap*, struct ns1__setxattr_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__setxattr_USCOREobject * SOAP_FMAC4 soap_in_ns1__setxattr_USCOREobject(struct soap*, const char*, struct ns1__setxattr_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__setxattr_USCOREobjectResponse
#define SOAP_TYPE_ns1__setxattr_USCOREobjectResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__setxattr_USCOREobjectResponse(struct soap*, struct ns1__setxattr_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__setxattr_USCOREobjectResponse(struct soap*, const struct ns1__setxattr_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__setxattr_USCOREobjectResponse(struct soap*, const struct ns1__setxattr_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__setxattr_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__setxattr_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__setxattr_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__setxattr_USCOREobjectResponse(struct soap*, struct ns1__setxattr_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__setxattr_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__setxattr_USCOREobjectResponse(struct soap*, const char*, struct ns1__setxattr_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__unlock_USCOREobject
#define SOAP_TYPE_ns1__unlock_USCOREobject (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__unlock_USCOREobject(struct soap*, struct ns1__unlock_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__unlock_USCOREobject(struct soap*, const struct ns1__unlock_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__unlock_USCOREobject(struct soap*, const struct ns1__unlock_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__unlock_USCOREobject(struct soap*, const char*, int, const struct ns1__unlock_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__unlock_USCOREobject * SOAP_FMAC4 soap_get_ns1__unlock_USCOREobject(struct soap*, struct ns1__unlock_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__unlock_USCOREobject * SOAP_FMAC4 soap_in_ns1__unlock_USCOREobject(struct soap*, const char*, struct ns1__unlock_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__unlock_USCOREobjectResponse
#define SOAP_TYPE_ns1__unlock_USCOREobjectResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__unlock_USCOREobjectResponse(struct soap*, struct ns1__unlock_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__unlock_USCOREobjectResponse(struct soap*, const struct ns1__unlock_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__unlock_USCOREobjectResponse(struct soap*, const struct ns1__unlock_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__unlock_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__unlock_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__unlock_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__unlock_USCOREobjectResponse(struct soap*, struct ns1__unlock_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__unlock_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__unlock_USCOREobjectResponse(struct soap*, const char*, struct ns1__unlock_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__lock_USCOREobject
#define SOAP_TYPE_ns1__lock_USCOREobject (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__lock_USCOREobject(struct soap*, struct ns1__lock_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__lock_USCOREobject(struct soap*, const struct ns1__lock_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__lock_USCOREobject(struct soap*, const struct ns1__lock_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__lock_USCOREobject(struct soap*, const char*, int, const struct ns1__lock_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__lock_USCOREobject * SOAP_FMAC4 soap_get_ns1__lock_USCOREobject(struct soap*, struct ns1__lock_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__lock_USCOREobject * SOAP_FMAC4 soap_in_ns1__lock_USCOREobject(struct soap*, const char*, struct ns1__lock_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__lock_USCOREobjectResponse
#define SOAP_TYPE_ns1__lock_USCOREobjectResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__lock_USCOREobjectResponse(struct soap*, struct ns1__lock_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__lock_USCOREobjectResponse(struct soap*, const struct ns1__lock_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__lock_USCOREobjectResponse(struct soap*, const struct ns1__lock_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__lock_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__lock_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__lock_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__lock_USCOREobjectResponse(struct soap*, struct ns1__lock_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__lock_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__lock_USCOREobjectResponse(struct soap*, const char*, struct ns1__lock_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__replicate_USCOREobject
#define SOAP_TYPE_ns1__replicate_USCOREobject (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__replicate_USCOREobject(struct soap*, struct ns1__replicate_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__replicate_USCOREobject(struct soap*, const struct ns1__replicate_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__replicate_USCOREobject(struct soap*, const struct ns1__replicate_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__replicate_USCOREobject(struct soap*, const char*, int, const struct ns1__replicate_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__replicate_USCOREobject * SOAP_FMAC4 soap_get_ns1__replicate_USCOREobject(struct soap*, struct ns1__replicate_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__replicate_USCOREobject * SOAP_FMAC4 soap_in_ns1__replicate_USCOREobject(struct soap*, const char*, struct ns1__replicate_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__replicate_USCOREobjectResponse
#define SOAP_TYPE_ns1__replicate_USCOREobjectResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__replicate_USCOREobjectResponse(struct soap*, struct ns1__replicate_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__replicate_USCOREobjectResponse(struct soap*, const struct ns1__replicate_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__replicate_USCOREobjectResponse(struct soap*, const struct ns1__replicate_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__replicate_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__replicate_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__replicate_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__replicate_USCOREobjectResponse(struct soap*, struct ns1__replicate_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__replicate_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__replicate_USCOREobjectResponse(struct soap*, const char*, struct ns1__replicate_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__swap_USCOREobjects
#define SOAP_TYPE_ns1__swap_USCOREobjects (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__swap_USCOREobjects(struct soap*, struct ns1__swap_USCOREobjects *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__swap_USCOREobjects(struct soap*, const struct ns1__swap_USCOREobjects *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__swap_USCOREobjects(struct soap*, const struct ns1__swap_USCOREobjects *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__swap_USCOREobjects(struct soap*, const char*, int, const struct ns1__swap_USCOREobjects *, const char*);
SOAP_FMAC3 struct ns1__swap_USCOREobjects * SOAP_FMAC4 soap_get_ns1__swap_USCOREobjects(struct soap*, struct ns1__swap_USCOREobjects *, const char*, const char*);
SOAP_FMAC3 struct ns1__swap_USCOREobjects * SOAP_FMAC4 soap_in_ns1__swap_USCOREobjects(struct soap*, const char*, struct ns1__swap_USCOREobjects *, const char*);

#ifndef SOAP_TYPE_ns1__swap_USCOREobjectsResponse
#define SOAP_TYPE_ns1__swap_USCOREobjectsResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__swap_USCOREobjectsResponse(struct soap*, struct ns1__swap_USCOREobjectsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__swap_USCOREobjectsResponse(struct soap*, const struct ns1__swap_USCOREobjectsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__swap_USCOREobjectsResponse(struct soap*, const struct ns1__swap_USCOREobjectsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__swap_USCOREobjectsResponse(struct soap*, const char*, int, const struct ns1__swap_USCOREobjectsResponse *, const char*);
SOAP_FMAC3 struct ns1__swap_USCOREobjectsResponse * SOAP_FMAC4 soap_get_ns1__swap_USCOREobjectsResponse(struct soap*, struct ns1__swap_USCOREobjectsResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__swap_USCOREobjectsResponse * SOAP_FMAC4 soap_in_ns1__swap_USCOREobjectsResponse(struct soap*, const char*, struct ns1__swap_USCOREobjectsResponse *, const char*);

#ifndef SOAP_TYPE_ns1__rename_USCOREobject
#define SOAP_TYPE_ns1__rename_USCOREobject (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__rename_USCOREobject(struct soap*, struct ns1__rename_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__rename_USCOREobject(struct soap*, const struct ns1__rename_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__rename_USCOREobject(struct soap*, const struct ns1__rename_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__rename_USCOREobject(struct soap*, const char*, int, const struct ns1__rename_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__rename_USCOREobject * SOAP_FMAC4 soap_get_ns1__rename_USCOREobject(struct soap*, struct ns1__rename_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__rename_USCOREobject * SOAP_FMAC4 soap_in_ns1__rename_USCOREobject(struct soap*, const char*, struct ns1__rename_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__rename_USCOREobjectResponse
#define SOAP_TYPE_ns1__rename_USCOREobjectResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__rename_USCOREobjectResponse(struct soap*, struct ns1__rename_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__rename_USCOREobjectResponse(struct soap*, const struct ns1__rename_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__rename_USCOREobjectResponse(struct soap*, const struct ns1__rename_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__rename_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__rename_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__rename_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__rename_USCOREobjectResponse(struct soap*, struct ns1__rename_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__rename_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__rename_USCOREobjectResponse(struct soap*, const char*, struct ns1__rename_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ns1__create_USCOREobject
#define SOAP_TYPE_ns1__create_USCOREobject (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__create_USCOREobject(struct soap*, struct ns1__create_USCOREobject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__create_USCOREobject(struct soap*, const struct ns1__create_USCOREobject *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__create_USCOREobject(struct soap*, const struct ns1__create_USCOREobject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__create_USCOREobject(struct soap*, const char*, int, const struct ns1__create_USCOREobject *, const char*);
SOAP_FMAC3 struct ns1__create_USCOREobject * SOAP_FMAC4 soap_get_ns1__create_USCOREobject(struct soap*, struct ns1__create_USCOREobject *, const char*, const char*);
SOAP_FMAC3 struct ns1__create_USCOREobject * SOAP_FMAC4 soap_in_ns1__create_USCOREobject(struct soap*, const char*, struct ns1__create_USCOREobject *, const char*);

#ifndef SOAP_TYPE_ns1__create_USCOREobjectResponse
#define SOAP_TYPE_ns1__create_USCOREobjectResponse (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__create_USCOREobjectResponse(struct soap*, struct ns1__create_USCOREobjectResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__create_USCOREobjectResponse(struct soap*, const struct ns1__create_USCOREobjectResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__create_USCOREobjectResponse(struct soap*, const struct ns1__create_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__create_USCOREobjectResponse(struct soap*, const char*, int, const struct ns1__create_USCOREobjectResponse *, const char*);
SOAP_FMAC3 struct ns1__create_USCOREobjectResponse * SOAP_FMAC4 soap_get_ns1__create_USCOREobjectResponse(struct soap*, struct ns1__create_USCOREobjectResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__create_USCOREobjectResponse * SOAP_FMAC4 soap_in_ns1__create_USCOREobjectResponse(struct soap*, const char*, struct ns1__create_USCOREobjectResponse *, const char*);

#ifndef SOAP_TYPE_ArrayOfString
#define SOAP_TYPE_ArrayOfString (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfString(struct soap*, struct ArrayOfString *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfString(struct soap*, struct ArrayOfString const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfString(struct soap*, const struct ArrayOfString *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfString(struct soap*, const char*, int, const struct ArrayOfString *, const char*);
SOAP_FMAC3 struct ArrayOfString * SOAP_FMAC4 soap_get_ArrayOfString(struct soap*, struct ArrayOfString *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfString * SOAP_FMAC4 soap_in_ArrayOfString(struct soap*, const char*, struct ArrayOfString *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons1__stat_USCOREobjectResponse
#define SOAP_TYPE_PointerTons1__stat_USCOREobjectResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__stat_USCOREobjectResponse(struct soap*, struct ns1__stat_USCOREobjectResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__stat_USCOREobjectResponse(struct soap*, struct ns1__stat_USCOREobjectResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__stat_USCOREobjectResponse(struct soap*, const char *, int, struct ns1__stat_USCOREobjectResponse *const*, const char *);
SOAP_FMAC3 struct ns1__stat_USCOREobjectResponse ** SOAP_FMAC4 soap_get_PointerTons1__stat_USCOREobjectResponse(struct soap*, struct ns1__stat_USCOREobjectResponse **, const char*, const char*);
SOAP_FMAC3 struct ns1__stat_USCOREobjectResponse ** SOAP_FMAC4 soap_in_PointerTons1__stat_USCOREobjectResponse(struct soap*, const char*, struct ns1__stat_USCOREobjectResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__find_USCOREinstancesResponse
#define SOAP_TYPE_PointerTons1__find_USCOREinstancesResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__find_USCOREinstancesResponse(struct soap*, struct ns1__find_USCOREinstancesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__find_USCOREinstancesResponse(struct soap*, struct ns1__find_USCOREinstancesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__find_USCOREinstancesResponse(struct soap*, const char *, int, struct ns1__find_USCOREinstancesResponse *const*, const char *);
SOAP_FMAC3 struct ns1__find_USCOREinstancesResponse ** SOAP_FMAC4 soap_get_PointerTons1__find_USCOREinstancesResponse(struct soap*, struct ns1__find_USCOREinstancesResponse **, const char*, const char*);
SOAP_FMAC3 struct ns1__find_USCOREinstancesResponse ** SOAP_FMAC4 soap_in_PointerTons1__find_USCOREinstancesResponse(struct soap*, const char*, struct ns1__find_USCOREinstancesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__find_USCOREobjectsResponse
#define SOAP_TYPE_PointerTons1__find_USCOREobjectsResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__find_USCOREobjectsResponse(struct soap*, struct ns1__find_USCOREobjectsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__find_USCOREobjectsResponse(struct soap*, struct ns1__find_USCOREobjectsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__find_USCOREobjectsResponse(struct soap*, const char *, int, struct ns1__find_USCOREobjectsResponse *const*, const char *);
SOAP_FMAC3 struct ns1__find_USCOREobjectsResponse ** SOAP_FMAC4 soap_get_PointerTons1__find_USCOREobjectsResponse(struct soap*, struct ns1__find_USCOREobjectsResponse **, const char*, const char*);
SOAP_FMAC3 struct ns1__find_USCOREobjectsResponse ** SOAP_FMAC4 soap_in_PointerTons1__find_USCOREobjectsResponse(struct soap*, const char*, struct ns1__find_USCOREobjectsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__listxattr_USCOREobjectResponse
#define SOAP_TYPE_PointerTons1__listxattr_USCOREobjectResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__listxattr_USCOREobjectResponse(struct soap*, struct ns1__listxattr_USCOREobjectResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__listxattr_USCOREobjectResponse(struct soap*, struct ns1__listxattr_USCOREobjectResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__listxattr_USCOREobjectResponse(struct soap*, const char *, int, struct ns1__listxattr_USCOREobjectResponse *const*, const char *);
SOAP_FMAC3 struct ns1__listxattr_USCOREobjectResponse ** SOAP_FMAC4 soap_get_PointerTons1__listxattr_USCOREobjectResponse(struct soap*, struct ns1__listxattr_USCOREobjectResponse **, const char*, const char*);
SOAP_FMAC3 struct ns1__listxattr_USCOREobjectResponse ** SOAP_FMAC4 soap_in_PointerTons1__listxattr_USCOREobjectResponse(struct soap*, const char*, struct ns1__listxattr_USCOREobjectResponse **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfString
#define SOAP_TYPE_PointerToArrayOfString (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfString(struct soap*, struct ArrayOfString *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfString(struct soap*, struct ArrayOfString *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfString(struct soap*, const char *, int, struct ArrayOfString *const*, const char *);
SOAP_FMAC3 struct ArrayOfString ** SOAP_FMAC4 soap_get_PointerToArrayOfString(struct soap*, struct ArrayOfString **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfString ** SOAP_FMAC4 soap_in_PointerToArrayOfString(struct soap*, const char*, struct ArrayOfString **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
