
installdir = $(bindir)

install_files = \
	pstamp_cleanup.pl \
	pstamp_finish.pl \
	pstamp_insert_request.pl \
	pstamp_job_run.pl \
	pstamp_listjobs.pl \
	pstamp_new_request.sh \
	pstampparse.pl \
	pstamp_parser_run.pl \
	pstamp_queue_cleanup.pl \
	pstamp_queue_requests.pl \
	pstamp_queue_update_cleanup.pl \
	pstamp_request_file \
	pstamp_results_file.pl \
	pstamp_revert_request.pl \
	pstamp_runcommand.sh \
	pstamp_server_status \
	pstamp_save_server_status.pl \
	pstamp_webrequest.pl \
        pstamp_get_image_job.pl \
	psmkreq \
	psgetcalibinfo \
	psstatus \
	pstampstopfaulted \
	pstamp_checkdependent.pl \
	request_finish.pl \
	detectability_respond.pl \
	detect_query_read \
	detect_query_create \
	detect_response_create \
        dquery_job_run.pl \
        dquery_finish.pl \
        dqueryparse.pl \
	fakedresponse.pl

install_SCRIPTS = $(install_files)

ACLOCAL_AMFLAGS = -I m4
