#
# Root of the data store (where the directory hierarchy lives
#
<Directory "/data/ipp000.0/datastore/dsroot">

  DirectoryIndex /ds-cgi/dsindex.cgi

  #Options None

  # turn on server side includes
  Options +Includes

  # files will be processed for server side includes if they have the
  # executable bit set
  XBitHack on

  AddType text/plain .txt
  AddOutputFilter INCLUDES .txt

  AllowOverride None

  Order allow,deny
  Allow from all
</Directory>


#
# Location of the cgi scripts
#

<Directory "/data/ipp000.0/datastore/ds-cgi">
  Options ExecCGI


  Order allow,deny
  Allow from all
</Directory>

Alias       /ds     /data/ipp000.0/datastore/dsroot/
ScriptAlias /ds-cgi /data/ipp000.0/datastore/ds-cgi/

